name: generate github metrics

on:
  schedule:
    - cron: "0 1 * * *" 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Переконайся, що назва тут збігається з назвою в Settings -> Secrets
          token: ${{ secrets.METRICS_TOKEN }}
          user: VSanotskyi
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Kiev
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          
          filename: github-metrics.svg
          output_action: none

      - name: push metrics to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
